### PR TITLE
Updated sample data to 1.9.2.4

### PR DESCRIPTION
**Pull request by bluec**
Closes issue #8

### CODE REVIEW

**Comment by sreichel** [comment]
Merge please :)

**Comment by Vinai** [comment]
Thank you!

**Comment by Vinai** [comment]
Damn, I completely missed this PR originally, soooory it took so long!

**Comment by sreichel** [comment]
So i can remove my repo :)

Can this be used for OpenMage and N98-magerun?

- https://github.com/OpenMage/magento-lts/pull/1481#issuecomment-797756365 (copy to OpenMage?)
- https://github.com/netz98/n98-magerun/pull/1166

**Comment by Vinai** [comment]
I don't think I can answer that. What is required so they can be used with magerun and openmage?

**Pull request merged**
